format = """
[](#222d2d)\
$os\
$username\
[](bg:#0078d4 fg:#222d2d)\
$directory\
[](fg:#0078d4 bg:#faeb5d)\
$git_branch\
$git_status\
[](fg:#faeb5d bg:#00000000)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "#ffffff bg:#222d2d"
style_root = "#ffffff bg:#222d2d"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "#ffffff bg:#222d2d"
disabled = true # Disabled by default

[directory]
style = "#ffffff bg:#0078d4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "#000000 bg:#faeb5d"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "#000000 bg:#faeb5d"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[gradle]
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "✨"
format = '[ $symbol ]($style)'

[nim]
symbol = "󰆥 "
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
format = '[ $symbol ($version) ]($style)'